### ISSUE TITLE
TypeError when using React: Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by yonatanmn** [radubrehar/react-date-picker#11]
this repo is using react in dependencies , and not as peerDependencies.
Please look at this: 
http://stackoverflow.com/questions/27153166/typeerror-when-using-react-cannot-read-property-firstchild-of-undefined

**Comment by radubrehar** [comment]
Please see my comment at https://stackoverflow.com/questions/27153166/typeerror-when-using-react-cannot-read-property-firstchild-of-undefined/28581074#28581074

Do you end-up with including React twice?

**Comment by yonatanmn** [comment]
Inside react-date-picker nomde-module I had React.
When I deleted it (as suggested) it was ok.
