### ISSUE TITLE
Remove "react" dependency

### ISSUE THREAD

**Issue by slorber** [radubrehar/react-date-picker#12]
Hi,

I've had troubles with your lib because it depends on React and my app deepends on your lib and React.

It happens that this can lead to 2 duplicate versions of React being loaded at the same time, raising an error.

I'm not sure it's a good idea but what I can see from other popular libraries like Fluxxor or Reflux is that they do not depend on React in package.json, thus letting the client provide the version of React himself.

I think what we are looking is called "peerDependency"

http://blog.nodejs.org/2013/02/07/peer-dependencies/

**Comment by radubrehar** [comment]
I've published v 1.4.3 with both react  & momentjs moved to peerDependencies.

**Comment by slorber** [comment]
Hi

Thanks wll give it a try soon

**Comment by slorber** [comment]
thanks it works
