### ISSUE TITLE
On each click/render another "date-picker" is added to the className

### ISSUE THREAD

**Issue by protron** [radubrehar/react-date-picker#7]
Not a big issue, but if you start clicking anything that is not a date (e.g. header arrows, month selector, footer buttons) and then inspect the **class** of the main div, you will see something like:

    class=" date-picker date-picker date-picker date-picker date-picker"

If you then click on any date, the className seems to go back to just one " date-picker".

I guess the offending code is at [line 107 of /src/index.jsx](https://github.com/radubrehar/react-date-picker/blob/05db5a54fed7fb16d6915ccb1b8fe971b5a96bc4/src/index.jsx#L107)

**Comment by radubrehar** [comment]
Thank you for reporting. It is now fixed. Version 1.3.2 on npm contains the fix.
