### ISSUE TITLE
Clicking on a dp-prev or dp-next day navigates to that month without events

### ISSUE THREAD

**Issue by ogg** [radubrehar/react-date-picker#9]
...and this behaviour stops as soon as I've clicked nav buttons. This behaviour can be observed in the demo:

http://jslog.com/react-date-picker/

I think it is fine that clicking a day that is not in the current month navigates to that month, but then a) onNav or similar should be fired, and b) this should happen consistently, not only until a nav button is clicked.

**Comment by ogg** [comment]
I've recorded a screen video demonstrating the problem: https://www.dropbox.com/s/2ha9f17ca9c42i5/react-date-picker-bug.mp4?dl=0

**Comment by radubrehar** [comment]
Thanks a lot. Sorry for the delay on solving this. Tomorrow I will come with a fix for this and will release a new version of the picker.

**Comment by ogg** [comment]
Excellent, thanks very much.

**Comment by radubrehar** [comment]
We've had some issues with github, as they are facing a ddos attack, so please bear with us for this to be released next week. Thanks

**Comment by radubrehar** [comment]
Just fixed it. See version 1.4.4

**Comment by ogg** [comment]
Thanks, really appreciate it!
